#
# Copyright (c) 2021-2023. NICE Ltd. All rights reserved.
#
# Licensed under the NICE License;
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://github.com/nice-devone/nice-cxone-mobile-sdk-ios/blob/main/LICENSE
#
# TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE CXONE MOBILE SDK IS PROVIDED ON
# AN “AS IS” BASIS. NICE HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS
# OR IMPLIED, INCLUDING (WITHOUT LIMITATION) WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND TITLE.
#

include:
  - path: xcodegen/defaults.yml
    relativePaths: false
  - path: xcodegen/entitlements.yml
    relativePaths: false
  - path: xcodegen/infoPlist.yml
    relativePaths: false
  - path: xcodegen/packages.yml
    relativePaths: false
  - path: xcodegen/amazon.yml
    relativePaths: false
  - local.yml

options:
  createIntermediateGroups: true
  bundleIdPrefix: ${BUNDLE_PREFIX}
  deploymentTarget:
    iOS: "13"

name: iOSSDKExample

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_PREFIX}.sample

targetTemplates:
  Common:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    settings:
      base:
        PRODUCT_NAME: "SDK Demo"
    sources:
      - path: iOSSDKExample/Sources
      - path: iOSSDKExample/Supporting Files
    dependencies:
      - package: ActivityIndicator
      - package: ALProgressView
      - package: CXoneChatSDK
      - package: IQKeyboardManagerSwift
      - package: Kingfisher
      - package: MessageKit
      - package: SnapKit
      - package: PKCE
      - package: Swinject
      - package: SwinjectAutoregistration
      - package: Toast
    postCompileScripts:
      - script: |
          if [[ "$(uname -m)" == arm64 ]]; then
            export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftlint > /dev/null; then
            swiftlint --config .swiftlint.yml
          else
            echo "warning: SwiftLint not installed, run brew install swiftlint"
          fi
        name: Swiftlint
        basedOnDependencyAnalysis: false
      - script: |
          if [[ "$(uname -m)" == arm64 ]]; then
            export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftgen > /dev/null; then
            swiftgen config -c .swiftgen.yml
          else
            echo "warning: SwiftGen not installed, run brew install swiftgen"
          fi
          
        name: SwiftGen
        runOnlyWhenInstalling: true
        basedOnDependencyAnalysis: true

targets:
  iOSSDKExample:
    templates: [Common, Entitled, Info, Amazon]

schemes:
  iOSSDKExample:
    build:
      targets:
        iOSSDKExample: all
